name: Build APK

on: workflow_dispatch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.4"

      - name: Get packages
        run: flutter pub get

      - name: Added flutterfire
        run: dart pub global activate flutterfire_cli

      - name: Configure firebase
        run: flutterfire configure --platforms android,ios

      - name: Build APK
        run: flutter build apk
