name: Build APK

on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter 
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.4'

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk
